package:
  name: "genomenlp"
  version: "2.8.5"

source:
  git_rev: v2.8.5
  git_url: https://github.com/tyronechen/genomenlp.git
  # url: https://github.com/tyronechen/genomenlp/releases/download/{{ version }}/genomenlp-{{ version }}.tar.gz
  git_depth: 0

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  entry_points:
    - compare_empirical_tokens = genomenlp.compare_empirical_tokens:main
    - create_dataset_bio = genomenlp.create_dataset_bio:main
    - create_dataset_nlp = genomenlp.create_dataset_nlp:main
    - create_embedding_bio_sp = genomenlp.create_embedding_bio_sp:main
    - create_embedding_bio_kmers = genomenlp.create_embedding_bio_kmers:main
    - cross_validate = genomenlp.cross_validate:main
    - embedding_pipeline = genomenlp.embedding_pipeline:main
    - fit_powerlaw = genomenlp.fit_powerlaw:main
    - freq_pipeline = genomenlp.freq_pipeline:main
    - generate_synthetic = genomenlp.generate_synthetic:main
    - interpret = genomenlp.interpret:main
    - kmerise_bio = genomenlp.kmerise_bio:main
    - parse_sp_tokens = genomenlp.parse_sp_tokens:main
    - summarise_metrics = genomenlp.summarise_metrics:main
    - sweep = genomenlp.sweep:main
    - tokenise_bio = genomenlp.tokenise_bio:main
    - train = genomenlp.train:main

requirements:
  host:
    - python
    - setuptools
  build:
    - python
  run:
    - datasets==2.10.1
    - gensim==4.2.0
    - hyperopt==0.2.7
    - matplotlib==3.5.2
    - pandas==1.4.2
    - pytorch==1.10.0
    - ray-default==1.13.0
    - scikit-learn==1.1.1
    - scipy==1.10.1
    - screed==1.0.5
    - seaborn==0.11.2
    - sentencepiece==0.1.96
    - tabulate==0.9.0
    - tokenizers==0.12.1
    - tqdm==4.64.0
    - transformers==4.23.0
    - transformers-interpret==0.8.1
    - wandb==0.13.4
    - weightwatcher==0.6.4
    - xgboost==1.7.1
    - yellowbrick==1.3.post1

about:
  home: https://github.com/tyronechen/genomenlp
  license: MIT
  license_familY: MIT
  license_file: LICENSE
  summary: Empirical genomic data tokenisation and data-free deep-learning model evaluation.
  description: Remember to add the conda-forge channel during install
  dev_url: https://github.com/tyronechen/genomenlp
  doc_url: https://genomenlp.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - tyronechen
